"""Backward-compatible re-exports — prefer ``app.schemas.document``."""

from app.schemas.document import (  # noqa: F401
    Address,
    BillingPeriod,
    ConsumptionInfo,
    Direction,
    DocumentCategory,
    DocumentExtractionData,
    DocumentStatus,
    ExtractionMetadata,
    FiscalDocumentData,
    FiscalInfo,
    LineItem,
    OperationType,
    Origin,
    Party,
    PartyRole,
    PaymentInfo,
    TaxEntry,
    Withholding,
    WithholdingType,
)

__all__ = [
    "Address",
    "BillingPeriod",
    "ConsumptionInfo",
    "Direction",
    "DocumentCategory",
    "DocumentExtractionData",
    "DocumentStatus",
    "ExtractionMetadata",
    "FiscalDocumentData",
    "FiscalInfo",
    "LineItem",
    "OperationType",
    "Origin",
    "Party",
    "PartyRole",
    "PaymentInfo",
    "TaxEntry",
    "Withholding",
    "WithholdingType",
]
